Changed # separator for |
arkhn/AVC-Forms pull request #17
Opened 2021-03-15 14:01 UTC by BPierrick

2021-03-16 09:55 UTC, simonvadee reviewed
I would have used a constant to do that, what do you think ? You would have only one variable to change to do this.

2021-03-17 17:52 UTC, elsiehoffet-94 requested changes
Sorry I didn't see this any sooner! The separator we want to change is actually the comma between each variable, not the #. I wrote this issue to make it more clear #18. 
Thanks!

2021-03-31 10:43 UTC, simonvadee approved these changes
lgtm

2021-03-31 10:43 UTC, simonvadee commented on app/src/utils/formUtils.ts
> +  if (values.length !== ICTUS_FORMAT_CSV_COLUMN_KEYS_MAP.length - 2) {
why length - 2?

2021-04-01 11:01 UTC, merged